[[edge_functions]]
path = "/get-country"
function = "location"

## redirects
[[redirects]]
from = "/packs"
to = "/"
status = 301

[[redirects]]
from = "/help"
to = "/"
status = 301

# redirect old packs path to new
[[redirects]]
from = "/datapacks/*"
to = "/packs/:splat"
status = 301

[[redirects]]
from = "/resource_packs/*"
to = "/packs/:splat"
status = 301

[[redirects]]
from = "/maps/*"
to = "/packs/:splat"
status = 301

# redirect cruft subdomain to nbt crafting page
[[redirects]]
from = "https://craft.cmd-golem.com/"
to = "https://cmd-golem.com/help/nbt_crafting.html"
status = 200!

[[redirects]]
from = "https://cmd-golem.netlify.app/*"
to = "https://cmd-golem.com/:splat"
status = 301!