## redirects
[[redirects]]
from = "/packs"
to = "/"
status = 301

[[redirects]]
from = "/help"
to = "/"
status = 301

[[redirects]]
from = "/datapacks/*"
to = "/packs/:splat"
status = 301

[[redirects]]
from = "https://cmd-golem.netlify.app/*"
to = "https://cmd-golem.com/:splat"
status = 301
force = true